src/main/urls.py
from django.conf.urls import url, include
from .views import CatalogView, ProductDetailView, productSearchView, CreateEvaluation


urlpatterns = [
    url(r'^search/$',productSearchView, name = "search"),
    url(r'^create/$',CreateEvaluation.as_view(), name = "create"),
    url(r'^(?P<slug>[\w-]+)/$',ProductDetailView.as_view(), name = "details"),
    url(r'$',CatalogView.as_view(), name = "list")

]

src/shops/urls.py
from django.conf.urls import url, include
from .views import ShopDetailView, ShopListView


urlpatterns = [

    url(r'^(?P<pk>\d+)',ShopDetailView.as_view(), name = "details"),
    url(r'$',ShopListView.as_view(), name = "list")

]

src/ype/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^catalog/', include('main.urls', namespace = "catalog")),
    url(r'^shops/', include('shops.urls', namespace = "shops"))
]

src/main/models.py
from django.db import models
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse
from shops.models import ShopModel
from django.contrib.auth.models import User

# Create your models here.

class ProductModel(models.Model):
    user        = models.ForeignKey(User)
    shop        = models.ForeignKey(ShopModel, null=True, blank=True)
    name        = models.CharField(max_length = 120, null = False, blank = False)
    price       = models.FloatField(null = True, blank = True)
    category    = models.CharField(max_length = 120,null = True, blank = True)
    mark        = models.FloatField(verbose_name="Your mark:",null = False, blank = False)
    evaluation  = models.TextField(verbose_name="Your opinion:",null = False, blank = False)
    created     = models.DateTimeField(auto_now=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(null = True, blank = True)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ("catalog:details", kwargs = {"slug":self.slug})


def product_slug_receiver (sender, instance, *args , **kwargs):
    #slug is a combination of name and pk. So we dont to specify DONT_USE names.
    #DONT_USE = ['search','add','list']
    correct_name = instance.name.replace(" ","-").lower()
    product_id = str(instance.id)
    if not instance.slug:
        instance.slug = correct_name + product_id
        instance.save()

post_save.connect(product_slug_receiver, sender = ProductModel)

src/shops/models.py
from django.db import models
from django.core.urlresolvers import reverse 

# Create your models here.

class ShopModel(models.Model):
    name        = models.CharField(max_length = 120)
    city        = models.CharField(max_length = 120, null=True, blank=True)
    street      = models.CharField(max_length = 120, null=True, blank=True)   
    open_at     = models.CharField(max_length = 5, null=True, blank=True, help_text="In HH:MM format.") 
    close_at    = models.CharField(max_length = 5, null=True, blank=True, help_text="In HH:MM format.") 
    created     = models.DateTimeField(auto_now_add=True) 
    updated     = models.DateTimeField(auto_now=True)

    def __str__(self):
        try:
            return (self.name + " - " + self.city + ", " + self.street)
        except:
            return (self.name)

    def get_absolute_url(self):
        return reverse ("shops:details", kwargs = {"pk":self.pk})

src/main/forms.py
from django import forms

class SearchForm(forms.Form):
    search    = forms.CharField(required = True)

class CreateEvaluationForm(forms.Form):
    name        = forms.CharField(max_length = 120, required = True)
    price       = forms.FloatField(required = True)
    category    = forms.CharField(max_length = 120, required = True)
    mark        = forms.FloatField(required = True)
    evaluation  = forms.TextInput()

src/main/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, TemplateView, FormView
from .models import ProductModel
from .forms import SearchForm, CreateEvaluationForm
from django.db.models import Q
from shops.models import ShopModel

# Create your views here.

class CatalogView(ListView):
    template_name = "catalog.html"
    queryset = ProductModel.objects.all()

class ProductDetailView(DetailView):
    template_name = "details.html"
    queryset = ProductModel.objects.all()
    
    # detailview takes slug wihout def. it. (autom.)
   
    #   def get_object(self, *args , **kwargs):
    #     slug = self.kwargs.get('slug')
    #     obj = get_object_or_404(ProductModel, slug = slug)
    #     return obj



def productSearchView(request):

    template_name = "search.html"
    form = SearchForm(request.POST)
    search = None
    
    search = request.POST.get('search')
    
    if form.errors:
        print (form.errors)
        errors = form.errors
        context = {}
    
    if search != None:
        queryset = ProductModel.objects.filter(Q(name__icontains = search) | Q(name__icontains = search))
        queryset2 = ShopModel.objects.filter(Q(name__icontains = search) | Q(name__icontains = search))
        context = {'queryset' : queryset, 'queryset2' : queryset2}

    else:
        context = {}

    return render(request, template_name, context)

class CreateEvaluation(CreateView):
    template_name = "create.html"
    model = ProductModel
    fields = ['name','price','category','mark','evaluation']

src/shops/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView
from .models import ShopModel
# Create your views here.

class ShopListView(ListView):
    template_name="shop_list.html"
    queryset = ShopModel.objects.all()


class ShopDetailView(DetailView):
    template_name="shop_detail.html"
    queryset = ShopModel.objects.all()


class ShopCreateView(CreateView):
    pass

src/main/templates/catalog.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | catalog{% endblock head_title %}

{% block content %}

<h3>List of products:</h3>
{% for product in object_list %}

<li><a href='{{product.get_absolute_url}}'>{{product}}</a> ({{product.category}})</li>

</ul>
{% endfor %}

{% endblock content %}

src/main/templates/create.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | create{% endblock head_title %}

{% block content %}

<h3>Add a product evaluation</h3>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add!" />
</form>
{% endblock %}

src/main/templates/details.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | {{object.name}}{% endblock head_title %}

{% block content %}
<br></br>
<h3>{{object}}:</h3>
    <p><b>Price:</b> {{object.price}} zł</p>
    <p><b>Category:</b> {{object.category}} </p>
    <p><b>Mark:</b> {{object.mark}} /10</p>
    <p><b>Evaluation:</b> {{object.evaluation}}</p>
    <p><b>Created:</b> {{object.created}}</p>
    <p><b>Updated:</b> {{object.updated}}</p>

{% endblock content %}

src/main/templates/search.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | search{% endblock head_title %}

{% block content %}

<form method="post">  {% csrf_token %}
    <br>
    <h2>
    <input type="text" name="search" placeholder="I am looking for:"> <button type="submit">Search!</button>
    </br></h2>
</form>

<h3>Results:</h3>
{% for result in queryset %}
<ul>
<li><a href='{{result.get_absolute_url}}'>{{result}}</a> ({{result.category}})</li>
</ul>

{% endfor %}

{% for result in queryset2 %}
<ul>
<li><a href='{{result.get_absolute_url}}'>{{result}}</a></li>
</ul>

{% endfor %}


{% endblock content %}

src/shops/templates/shop_detail.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | {{object.name}}{% endblock head_title %}

{% block content %}
<br></br>
<h3>{{object.name}}:</h3>
    <p>{{object.city}}</p>
    <p>{{object.street}}</p>
{% endblock content %}

src/shops/templates/shop_list.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | catalog{% endblock head_title %}

{% block content %}

<h3>List of shops:</h3>
{% for shop in object_list %}

<li><a href='{{shop.get_absolute_url}}'>{{shop.name}}</a> ({{shop.city}}, {{shop.street}})</li>

</ul>
{% endfor %}

{% endblock content %}

src/templates/about.html
{% extends "base.html" %}
{% block head_title %} {{block.super}} | about{% endblock head_title %}

{% block content %}
</br>
<h3>Hello!</h3>
<p>My name is Patryk and this is my first django project.</p>
<p>YPE allows you to save your opinion about any product.</p>
<p>For instance, you can evaluate tea which you are drinking right now.</p>
<p>I belive that YPE project would improve my skills and help me in my further career as a django developer</p>
<p>You can find more details about YPE on my <a href='https://github.com/PatrykJanMatlak/ype-app'>github.</a></p>
<p>Contact email: <a href="mailto:patrykjan.matlak@gmail.com">patrykjan.matlak@gmail.com</a></p>
{% endblock %}

src/templates/base.html
<!doctype html>
<html>
<head>
{% include 'snippets/css.html' %}

<title>
    {% block head_title %} 
    YPE
    {% endblock head_title %}
</title>

</head>

<body>

    {% include 'snippets/nav.html' %}

    <div class='container'>
        {% block content %}
        {% endblock %}
    </div>

    {% include 'snippets/js.html' %}

</body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | home{% endblock head_title %}

src/templates/search.html
{% extends "base.html" %}

{% block head_title %} {{block.super}} | search{% endblock head_title %}

{% block content %}

<form method="post">  {% csrf_token %}
    <br>
    <h2>
    <input type="text" name="search" placeholder="I am looking for:"> <button type="submit">Search!</button>
    </br></h2>
</form>


<h3>Results:</h3>
{% for result in queryset %}
<ul>
<li><a href='{{result.get_absolute_url}}'>{{result}}</a> ({{result.category}})</li>
</ul>

{% endfor %}

{% endblock content %}

src/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class='container'>
    <h1>YOUR PRODUCT EVALUATION</h1>
    
    <a href='{% url "home" %}'>Home</a> ||
    <a href='{% url "about" %}'>About</a> ||
    <a href='{% url "catalog:search" %}'>Search</a> ||
    <!-- <a href='{% url "catalog:create" %}'>Add</a> ||-->
    <a href='{% url "catalog:list" %}'>Catalog</a> ||
    <a href='{% url "shops:list" %}'>Shops</a> ||

    </div>